use_gpu: True
device: 0
early_stop:
    patience: 20
federate:
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 100
  share_local_model: False
seed: 0
data:
  root: data/
  # type: graph_multi_domain_mix
  type: cikmcup
  # pre_transforms: constant_feat
  # pre_transform: [['RandomScale',{'scales':[(0.5,1.5)]}]]
  pre_transform: []
model:
  dropout: 0.3
  type: gin
  hidden: 64
  out_channels: 0
  task: graph
flitplus:
  tmpFed: 0.5
  factor_ema: 0.8
personalization:
  # local_param: ['encoder_atom', 'encoder', 'clf']   # to handle size-different pre & post layers
  local_param: [ 'encoder_atom', 'encoder', 'clf', 'norms','linear'] #,'gnn.conv.1']  # pre, post + FedBN
train:
  local_update_steps: 16
  optimizer:
    lr: 0.25
    momentum: 0.9
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: flitplustrainer #graphminibatch_trainer
eval:
  # freq: 5
  # metrics: ['acc', 'correct']
  freq: 5
  metrics: ['imp_ratio','acc']
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  split: ['test', 'val']
